### PR TITLE
Use TypeScript and D3 v5

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
We will merge and iterate unless @cekees has some feedback on this.

**Comment by cekees** [comment]
Yes, please proceed. I’ll try to get caught up next week.

**Comment by davidbrochart** [comment]
Thanks Chris, I will go ahead and make releases too. Not sure I have the rights to do it on PyPI and NPM though.

**Comment by davidbrochart** [comment]
@cekees I cannot publish to NPM or PyPI, could you please give me the permissions?

**Pull request merged**
